; Auto-generated. Do not edit!


(cl:in-package opt-msg)


;//! \htmlinclude Bru_irb_rotateBoltGoal.msg.html

(cl:defclass <Bru_irb_rotateBoltGoal> (roslisp-msg-protocol:ros-message)
  ((angle
    :reader angle
    :initarg :angle
    :type cl:float
    :initform 0.0))
)

(cl:defclass Bru_irb_rotateBoltGoal (<Bru_irb_rotateBoltGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Bru_irb_rotateBoltGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Bru_irb_rotateBoltGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name opt-msg:<Bru_irb_rotateBoltGoal> is deprecated: use opt-msg:Bru_irb_rotateBoltGoal instead.")))

(cl:ensure-generic-function 'angle-val :lambda-list '(m))
(cl:defmethod angle-val ((m <Bru_irb_rotateBoltGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opt-msg:angle-val is deprecated.  Use opt-msg:angle instead.")
  (angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Bru_irb_rotateBoltGoal>) ostream)
  "Serializes a message object of type '<Bru_irb_rotateBoltGoal>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Bru_irb_rotateBoltGoal>) istream)
  "Deserializes a message object of type '<Bru_irb_rotateBoltGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'angle) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Bru_irb_rotateBoltGoal>)))
  "Returns string type for a message object of type '<Bru_irb_rotateBoltGoal>"
  "opt/Bru_irb_rotateBoltGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Bru_irb_rotateBoltGoal)))
  "Returns string type for a message object of type 'Bru_irb_rotateBoltGoal"
  "opt/Bru_irb_rotateBoltGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Bru_irb_rotateBoltGoal>)))
  "Returns md5sum for a message object of type '<Bru_irb_rotateBoltGoal>"
  "4edb55038e2b888976a0c0c56935341c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Bru_irb_rotateBoltGoal)))
  "Returns md5sum for a message object of type 'Bru_irb_rotateBoltGoal"
  "4edb55038e2b888976a0c0c56935341c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Bru_irb_rotateBoltGoal>)))
  "Returns full string definition for message of type '<Bru_irb_rotateBoltGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%float64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Bru_irb_rotateBoltGoal)))
  "Returns full string definition for message of type 'Bru_irb_rotateBoltGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%float64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Bru_irb_rotateBoltGoal>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Bru_irb_rotateBoltGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Bru_irb_rotateBoltGoal
    (cl:cons ':angle (angle msg))
))
