; Auto-generated. Do not edit!


(cl:in-package opt-msg)


;//! \htmlinclude Bru_irb_correctPositionActionGoal.msg.html

(cl:defclass <Bru_irb_correctPositionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type opt-msg:Bru_irb_correctPositionGoal
    :initform (cl:make-instance 'opt-msg:Bru_irb_correctPositionGoal)))
)

(cl:defclass Bru_irb_correctPositionActionGoal (<Bru_irb_correctPositionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Bru_irb_correctPositionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Bru_irb_correctPositionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name opt-msg:<Bru_irb_correctPositionActionGoal> is deprecated: use opt-msg:Bru_irb_correctPositionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <Bru_irb_correctPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opt-msg:header-val is deprecated.  Use opt-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <Bru_irb_correctPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opt-msg:goal_id-val is deprecated.  Use opt-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <Bru_irb_correctPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader opt-msg:goal-val is deprecated.  Use opt-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Bru_irb_correctPositionActionGoal>) ostream)
  "Serializes a message object of type '<Bru_irb_correctPositionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Bru_irb_correctPositionActionGoal>) istream)
  "Deserializes a message object of type '<Bru_irb_correctPositionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Bru_irb_correctPositionActionGoal>)))
  "Returns string type for a message object of type '<Bru_irb_correctPositionActionGoal>"
  "opt/Bru_irb_correctPositionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Bru_irb_correctPositionActionGoal)))
  "Returns string type for a message object of type 'Bru_irb_correctPositionActionGoal"
  "opt/Bru_irb_correctPositionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Bru_irb_correctPositionActionGoal>)))
  "Returns md5sum for a message object of type '<Bru_irb_correctPositionActionGoal>"
  "249264aba57f7821218fbc90d41f5f41")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Bru_irb_correctPositionActionGoal)))
  "Returns md5sum for a message object of type 'Bru_irb_correctPositionActionGoal"
  "249264aba57f7821218fbc90d41f5f41")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Bru_irb_correctPositionActionGoal>)))
  "Returns full string definition for message of type '<Bru_irb_correctPositionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%Bru_irb_correctPositionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: opt/Bru_irb_correctPositionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%float64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Bru_irb_correctPositionActionGoal)))
  "Returns full string definition for message of type 'Bru_irb_correctPositionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%Bru_irb_correctPositionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: opt/Bru_irb_correctPositionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# This is an action definition file, which has three parts: the goal~%# the result, and the feedback.~%# Part 1: the goal.~%#~%# The angle in degree the robot to turn, sent by client main~%float64 angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Bru_irb_correctPositionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Bru_irb_correctPositionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'Bru_irb_correctPositionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
