// Generated by gencpp from file abb_irb120_support/Forces.msg
// DO NOT EDIT!


#ifndef ABB_IRB120_SUPPORT_MESSAGE_FORCES_H
#define ABB_IRB120_SUPPORT_MESSAGE_FORCES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace abb_irb120_support
{
template <class ContainerAllocator>
struct Forces_
{
  typedef Forces_<ContainerAllocator> Type;

  Forces_()
    : p()  {
      p.assign(0.0);
  }
  Forces_(const ContainerAllocator& _alloc)
    : p()  {
  (void)_alloc;
      p.assign(0.0);
  }



   typedef boost::array<double, 3>  _p_type;
  _p_type p;





  typedef boost::shared_ptr< ::abb_irb120_support::Forces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::abb_irb120_support::Forces_<ContainerAllocator> const> ConstPtr;

}; // struct Forces_

typedef ::abb_irb120_support::Forces_<std::allocator<void> > Forces;

typedef boost::shared_ptr< ::abb_irb120_support::Forces > ForcesPtr;
typedef boost::shared_ptr< ::abb_irb120_support::Forces const> ForcesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::abb_irb120_support::Forces_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::abb_irb120_support::Forces_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace abb_irb120_support

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'abb_irb120_support': ['/home/gijs/bolts_ws/src/irb/abb_irb120_support/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb120_support::Forces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::abb_irb120_support::Forces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb120_support::Forces_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::abb_irb120_support::Forces_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb120_support::Forces_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::abb_irb120_support::Forces_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::abb_irb120_support::Forces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1abbaca176899a0863a2922ff57df9ac";
  }

  static const char* value(const ::abb_irb120_support::Forces_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1abbaca176899a08ULL;
  static const uint64_t static_value2 = 0x63a2922ff57df9acULL;
};

template<class ContainerAllocator>
struct DataType< ::abb_irb120_support::Forces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abb_irb120_support/Forces";
  }

  static const char* value(const ::abb_irb120_support::Forces_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::abb_irb120_support::Forces_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] p\n\
";
  }

  static const char* value(const ::abb_irb120_support::Forces_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::abb_irb120_support::Forces_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.p);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Forces_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::abb_irb120_support::Forces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::abb_irb120_support::Forces_<ContainerAllocator>& v)
  {
    s << indent << "p[]" << std::endl;
    for (size_t i = 0; i < v.p.size(); ++i)
    {
      s << indent << "  p[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.p[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ABB_IRB120_SUPPORT_MESSAGE_FORCES_H
