# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vision/imageCircleData.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import vision.msg

class imageCircleData(genpy.Message):
  _md5sum = "f8a2a99d547045d060df3120b6af8431"
  _type = "vision/imageCircleData"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Message file which can be used to transfer a vector of circle data. For more info see VectorData.msg
# Date: 04-12-2018
# By: Giel Oomen

string vector_name		# Name of the vector
VectorData[] allHolesDataVec	# Vector of 'VectorData' structs (from VectorData.msg)


================================================================================
MSG: vision/VectorData
# This message contains the structure of which the vector in imageCircleData.msg is made of. 
# One place in the vector contains x, y, z and size values of one circle detected in the image.
# Date: 04-12-2018	
# By Giel Oomen

float64 x	# Circle position on x-axis
float64 y	# Circle position on y-axis
float64 z	# Circle position on z-axis (depth in meters)
float64 size	# Circle size 
"""
  __slots__ = ['vector_name','allHolesDataVec']
  _slot_types = ['string','vision/VectorData[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vector_name,allHolesDataVec

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imageCircleData, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vector_name is None:
        self.vector_name = ''
      if self.allHolesDataVec is None:
        self.allHolesDataVec = []
    else:
      self.vector_name = ''
      self.allHolesDataVec = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.vector_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.allHolesDataVec)
      buff.write(_struct_I.pack(length))
      for val1 in self.allHolesDataVec:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.allHolesDataVec is None:
        self.allHolesDataVec = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vector_name = str[start:end].decode('utf-8')
      else:
        self.vector_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.allHolesDataVec = []
      for i in range(0, length):
        val1 = vision.msg.VectorData()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.size,) = _get_struct_4d().unpack(str[start:end])
        self.allHolesDataVec.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.vector_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.allHolesDataVec)
      buff.write(_struct_I.pack(length))
      for val1 in self.allHolesDataVec:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.allHolesDataVec is None:
        self.allHolesDataVec = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vector_name = str[start:end].decode('utf-8')
      else:
        self.vector_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.allHolesDataVec = []
      for i in range(0, length):
        val1 = vision.msg.VectorData()
        _x = val1
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.size,) = _get_struct_4d().unpack(str[start:end])
        self.allHolesDataVec.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
