// Generated by gencpp from file opt/Bru_irb_rotateBoltResult.msg
// DO NOT EDIT!


#ifndef OPT_MESSAGE_BRU_IRB_ROTATEBOLTRESULT_H
#define OPT_MESSAGE_BRU_IRB_ROTATEBOLTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opt
{
template <class ContainerAllocator>
struct Bru_irb_rotateBoltResult_
{
  typedef Bru_irb_rotateBoltResult_<ContainerAllocator> Type;

  Bru_irb_rotateBoltResult_()
    : time_elapsed()
    , updates_n(0)  {
    }
  Bru_irb_rotateBoltResult_(const ContainerAllocator& _alloc)
    : time_elapsed()
    , updates_n(0)  {
  (void)_alloc;
    }



   typedef ros::Duration _time_elapsed_type;
  _time_elapsed_type time_elapsed;

   typedef uint32_t _updates_n_type;
  _updates_n_type updates_n;





  typedef boost::shared_ptr< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> const> ConstPtr;

}; // struct Bru_irb_rotateBoltResult_

typedef ::opt::Bru_irb_rotateBoltResult_<std::allocator<void> > Bru_irb_rotateBoltResult;

typedef boost::shared_ptr< ::opt::Bru_irb_rotateBoltResult > Bru_irb_rotateBoltResultPtr;
typedef boost::shared_ptr< ::opt::Bru_irb_rotateBoltResult const> Bru_irb_rotateBoltResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'opt': ['/home/gijs/bolts_ws/src/opt/msg', '/home/gijs/bolts_ws/devel/share/opt/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec7b9dd60f0cbf3a48147f1dd0e2c305";
  }

  static const char* value(const ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec7b9dd60f0cbf3aULL;
  static const uint64_t static_value2 = 0x48147f1dd0e2c305ULL;
};

template<class ContainerAllocator>
struct DataType< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt/Bru_irb_rotateBoltResult";
  }

  static const char* value(const ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Part 2: the result, sent by action server unpon completion\n\
#\n\
# How much time used\n\
duration time_elapsed\n\
# How many updates thrown in total\n\
uint32 updates_n\n\
";
  }

  static const char* value(const ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_elapsed);
      stream.next(m.updates_n);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bru_irb_rotateBoltResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt::Bru_irb_rotateBoltResult_<ContainerAllocator>& v)
  {
    s << indent << "time_elapsed: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_elapsed);
    s << indent << "updates_n: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.updates_n);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MESSAGE_BRU_IRB_ROTATEBOLTRESULT_H
