// Generated by gencpp from file opt/OptoForceData.msg
// DO NOT EDIT!


#ifndef OPT_MESSAGE_OPTOFORCEDATA_H
#define OPT_MESSAGE_OPTOFORCEDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace opt
{
template <class ContainerAllocator>
struct OptoForceData_
{
  typedef OptoForceData_<ContainerAllocator> Type;

  OptoForceData_()
    : fx(0.0)
    , fy(0.0)
    , fz(0.0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)  {
    }
  OptoForceData_(const ContainerAllocator& _alloc)
    : fx(0.0)
    , fy(0.0)
    , fz(0.0)
    , tx(0.0)
    , ty(0.0)
    , tz(0.0)  {
  (void)_alloc;
    }



   typedef double _fx_type;
  _fx_type fx;

   typedef double _fy_type;
  _fy_type fy;

   typedef double _fz_type;
  _fz_type fz;

   typedef double _tx_type;
  _tx_type tx;

   typedef double _ty_type;
  _ty_type ty;

   typedef double _tz_type;
  _tz_type tz;





  typedef boost::shared_ptr< ::opt::OptoForceData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::opt::OptoForceData_<ContainerAllocator> const> ConstPtr;

}; // struct OptoForceData_

typedef ::opt::OptoForceData_<std::allocator<void> > OptoForceData;

typedef boost::shared_ptr< ::opt::OptoForceData > OptoForceDataPtr;
typedef boost::shared_ptr< ::opt::OptoForceData const> OptoForceDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::opt::OptoForceData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::opt::OptoForceData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace opt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'opt': ['/home/gijs/bolts_ws/src/opt/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::opt::OptoForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::opt::OptoForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt::OptoForceData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::opt::OptoForceData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt::OptoForceData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::opt::OptoForceData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::opt::OptoForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6da1f4bb463d64b2399f31589512a6f";
  }

  static const char* value(const ::opt::OptoForceData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6da1f4bb463d64bULL;
  static const uint64_t static_value2 = 0x2399f31589512a6fULL;
};

template<class ContainerAllocator>
struct DataType< ::opt::OptoForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "opt/OptoForceData";
  }

  static const char* value(const ::opt::OptoForceData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::opt::OptoForceData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 fx\n\
float64 fy\n\
float64 fz\n\
float64 tx\n\
float64 ty\n\
float64 tz\n\
";
  }

  static const char* value(const ::opt::OptoForceData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::opt::OptoForceData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fx);
      stream.next(m.fy);
      stream.next(m.fz);
      stream.next(m.tx);
      stream.next(m.ty);
      stream.next(m.tz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OptoForceData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::opt::OptoForceData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::opt::OptoForceData_<ContainerAllocator>& v)
  {
    s << indent << "fx: ";
    Printer<double>::stream(s, indent + "  ", v.fx);
    s << indent << "fy: ";
    Printer<double>::stream(s, indent + "  ", v.fy);
    s << indent << "fz: ";
    Printer<double>::stream(s, indent + "  ", v.fz);
    s << indent << "tx: ";
    Printer<double>::stream(s, indent + "  ", v.tx);
    s << indent << "ty: ";
    Printer<double>::stream(s, indent + "  ", v.ty);
    s << indent << "tz: ";
    Printer<double>::stream(s, indent + "  ", v.tz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPT_MESSAGE_OPTOFORCEDATA_H
