// Generated by gencpp from file weiss_gripper_ieg76/SetForceRequest.msg
// DO NOT EDIT!


#ifndef WEISS_GRIPPER_IEG76_MESSAGE_SETFORCEREQUEST_H
#define WEISS_GRIPPER_IEG76_MESSAGE_SETFORCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weiss_gripper_ieg76
{
template <class ContainerAllocator>
struct SetForceRequest_
{
  typedef SetForceRequest_<ContainerAllocator> Type;

  SetForceRequest_()
    : grasping_force(0)  {
    }
  SetForceRequest_(const ContainerAllocator& _alloc)
    : grasping_force(0)  {
  (void)_alloc;
    }



   typedef uint8_t _grasping_force_type;
  _grasping_force_type grasping_force;





  typedef boost::shared_ptr< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetForceRequest_

typedef ::weiss_gripper_ieg76::SetForceRequest_<std::allocator<void> > SetForceRequest;

typedef boost::shared_ptr< ::weiss_gripper_ieg76::SetForceRequest > SetForceRequestPtr;
typedef boost::shared_ptr< ::weiss_gripper_ieg76::SetForceRequest const> SetForceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace weiss_gripper_ieg76

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00a501f650eb4f44e5fb8819084fd8df";
  }

  static const char* value(const ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00a501f650eb4f44ULL;
  static const uint64_t static_value2 = 0xe5fb8819084fd8dfULL;
};

template<class ContainerAllocator>
struct DataType< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weiss_gripper_ieg76/SetForceRequest";
  }

  static const char* value(const ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 grasping_force\n\
";
  }

  static const char* value(const ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasping_force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetForceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weiss_gripper_ieg76::SetForceRequest_<ContainerAllocator>& v)
  {
    s << indent << "grasping_force: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.grasping_force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEISS_GRIPPER_IEG76_MESSAGE_SETFORCEREQUEST_H
