// Auto-generated. Do not edit!

// (in-package opt.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Bru_irb_rotateBoltActionGoal = require('./Bru_irb_rotateBoltActionGoal.js');
let Bru_irb_rotateBoltActionResult = require('./Bru_irb_rotateBoltActionResult.js');
let Bru_irb_rotateBoltActionFeedback = require('./Bru_irb_rotateBoltActionFeedback.js');

//-----------------------------------------------------------

class Bru_irb_rotateBoltAction {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.action_goal = null;
      this.action_result = null;
      this.action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('action_goal')) {
        this.action_goal = initObj.action_goal
      }
      else {
        this.action_goal = new Bru_irb_rotateBoltActionGoal();
      }
      if (initObj.hasOwnProperty('action_result')) {
        this.action_result = initObj.action_result
      }
      else {
        this.action_result = new Bru_irb_rotateBoltActionResult();
      }
      if (initObj.hasOwnProperty('action_feedback')) {
        this.action_feedback = initObj.action_feedback
      }
      else {
        this.action_feedback = new Bru_irb_rotateBoltActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type Bru_irb_rotateBoltAction
    // Serialize message field [action_goal]
    bufferOffset = Bru_irb_rotateBoltActionGoal.serialize(obj.action_goal, buffer, bufferOffset);
    // Serialize message field [action_result]
    bufferOffset = Bru_irb_rotateBoltActionResult.serialize(obj.action_result, buffer, bufferOffset);
    // Serialize message field [action_feedback]
    bufferOffset = Bru_irb_rotateBoltActionFeedback.serialize(obj.action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type Bru_irb_rotateBoltAction
    let len;
    let data = new Bru_irb_rotateBoltAction(null);
    // Deserialize message field [action_goal]
    data.action_goal = Bru_irb_rotateBoltActionGoal.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_result]
    data.action_result = Bru_irb_rotateBoltActionResult.deserialize(buffer, bufferOffset);
    // Deserialize message field [action_feedback]
    data.action_feedback = Bru_irb_rotateBoltActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += Bru_irb_rotateBoltActionGoal.getMessageSize(object.action_goal);
    length += Bru_irb_rotateBoltActionResult.getMessageSize(object.action_result);
    length += Bru_irb_rotateBoltActionFeedback.getMessageSize(object.action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'opt/Bru_irb_rotateBoltAction';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '35d38dbd42a980847473ec6743160f8f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Bru_irb_rotateBoltActionGoal action_goal
    Bru_irb_rotateBoltActionResult action_result
    Bru_irb_rotateBoltActionFeedback action_feedback
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltActionGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalID goal_id
    Bru_irb_rotateBoltGoal goal
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltGoal
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # This is an action definition file, which has three parts: the goal
    # the result, and the feedback.
    # Part 1: the goal.
    #
    # The angle in degree the robot to turn, sent by client main
    float64 angle
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltActionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    Bru_irb_rotateBoltResult result
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Part 2: the result, sent by action server unpon completion
    #
    # How much time used
    duration time_elapsed
    # How many updates thrown in total
    uint32 updates_n
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltActionFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    Bru_irb_rotateBoltFeedback feedback
    
    ================================================================================
    MSG: opt/Bru_irb_rotateBoltFeedback
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Part 3: the feedback,to be sent periodically by server
    #
    # The amount of time elapsed from the start
    duration time_elapsed
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new Bru_irb_rotateBoltAction(null);
    if (msg.action_goal !== undefined) {
      resolved.action_goal = Bru_irb_rotateBoltActionGoal.Resolve(msg.action_goal)
    }
    else {
      resolved.action_goal = new Bru_irb_rotateBoltActionGoal()
    }

    if (msg.action_result !== undefined) {
      resolved.action_result = Bru_irb_rotateBoltActionResult.Resolve(msg.action_result)
    }
    else {
      resolved.action_result = new Bru_irb_rotateBoltActionResult()
    }

    if (msg.action_feedback !== undefined) {
      resolved.action_feedback = Bru_irb_rotateBoltActionFeedback.Resolve(msg.action_feedback)
    }
    else {
      resolved.action_feedback = new Bru_irb_rotateBoltActionFeedback()
    }

    return resolved;
    }
};

module.exports = Bru_irb_rotateBoltAction;
